# Generated by Django 6.0 on 2025-12-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('SALON_OWNER', 'Salon Owner'), ('CUSTOMER', 'Customer'), ('STAFF', 'Staff')], default='SALON_OWNER', max_length=20),
        ),
    ]
