# Generated by Django 6.0 on 2025-12-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, help_text='Firebase UID', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SALON_OWNER', 'Salon Owner'), ('EMPLOYEE', 'Employee'), ('CUSTOMER', 'Customer')], default='SALON_OWNER', max_length=20),
        ),
    ]
