# Generated by Django 6.0 on 2025-12-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_firebase_uid_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SALON_OWNER', 'Salon Owner'), ('EMPLOYEE', 'Employee'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
