# Generated by Django 6.0 on 2026-01-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SALON_OWNER', 'Salon Owner'), ('EMPLOYEE', 'Employee'), ('CUSTOMER', 'Customer')], default='SALON_OWNER', max_length=20),
        ),
    ]
