# Generated by Django 6.0 on 2025-12-24 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_remove_salon_admin_salon_is_open_salon_owner_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('hair', 'Hair'), ('spa', 'Spa'), ('nails', 'Nails'), ('facial', 'Facial'), ('massage', 'Massage'), ('waxing', 'Waxing'), ('makeup', 'Makeup'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['salon', 'is_active'], name='services_se_salon_i_8869bc_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='services_se_categor_d1e3c4_idx'),
        ),
    ]
