# Generated by Django 6.0 on 2026-01-26 05:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(blank=True, help_text='Full name of the customer', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, help_text='Street address')),
                ('city', models.CharField(blank=True, help_text='City name', max_length=100)),
                ('pincode', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=10)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NOT_SPECIFIED', 'Not Specified')], default='NOT_SPECIFIED', help_text='Gender', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Customer profile picture', null=True, upload_to='customer_profiles/')),
                ('preferred_services', models.JSONField(blank=True, default=list, help_text='List of preferred service IDs')),
                ('preferred_salons', models.JSONField(blank=True, default=list, help_text='List of preferred salon IDs')),
                ('is_verified', models.BooleanField(default=False, help_text='Phone/email verification status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['city', 'pincode'], name='customers_c_city_9b444f_idx')],
            },
        ),
    ]
