# Generated by Django 6.0 on 2026-01-29 15:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_booking_price_alter_booking_end_time'),
        ('salons', '0005_salon_city_salon_latitude_salon_longitude_and_more'),
        ('services', '0002_alter_service_options_service_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Overall rating (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, help_text='Review title/summary', max_length=200)),
                ('comment', models.TextField(help_text='Detailed review text')),
                ('service_quality_rating', models.IntegerField(blank=True, help_text='Service quality rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('staff_behavior_rating', models.IntegerField(blank=True, help_text='Staff behavior rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ambiance_rating', models.IntegerField(blank=True, help_text='Ambiance/atmosphere rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('value_for_money_rating', models.IntegerField(blank=True, help_text='Value for money rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_verified', models.BooleanField(default=False, help_text='Verified review (linked to actual booking)')),
                ('is_approved', models.BooleanField(default=True, help_text='Admin approved (for moderation)')),
                ('is_edited', models.BooleanField(default=False, help_text='Review was edited after posting')),
                ('owner_reply', models.TextField(blank=True, help_text="Salon owner's response to review")),
                ('owner_replied_at', models.DateTimeField(blank=True, help_text='When owner replied', null=True)),
                ('helpful_count', models.IntegerField(default=0, help_text='Number of users who found this helpful')),
                ('not_helpful_count', models.IntegerField(default=0, help_text="Number of users who didn't find this helpful")),
                ('images', models.JSONField(blank=True, default=list, help_text='Review images URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, help_text='Booking this review is for (ensures verified reviews)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='bookings.booking')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='salons.salon')),
                ('service', models.ForeignKey(blank=True, help_text='Specific service being reviewed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpfulness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(help_text='True if helpful, False if not helpful')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpfulness_votes', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Helpfulness Vote',
                'verbose_name_plural': 'Review Helpfulness Votes',
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or fake review'), ('offensive', 'Offensive language'), ('irrelevant', 'Irrelevant content'), ('personal', 'Personal information'), ('duplicate', 'Duplicate review'), ('other', 'Other reason')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review')),
            ],
            options={
                'verbose_name': 'Review Report',
                'verbose_name_plural': 'Review Reports',
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['salon', '-created_at'], name='reviews_rev_salon_i_6ea13c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['service', '-created_at'], name='reviews_rev_service_0d3aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='reviews_rev_user_id_a65d48_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_approved', '-created_at'], name='reviews_rev_is_appr_dbec64_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('booking',), name='unique_review_per_booking'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpfulness',
            unique_together={('review', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewreport',
            unique_together={('review', 'reported_by')},
        ),
    ]
