# Generated by Django 6.0 on 2026-01-28 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('salons', '0005_salon_city_salon_latitude_salon_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin Chat History', 'verbose_name_plural': 'Admin Chat Histories'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-session_start'], 'verbose_name': 'Admin Chat Session', 'verbose_name_plural': 'Admin Chat Sessions'},
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_chat_history', to='salons.salon'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_chat_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_chat_sessions', to='salons.salon'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('message_count', models.IntegerField(default=0)),
                ('actions_taken', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Chat Session',
                'verbose_name_plural': 'User Chat Sessions',
                'ordering': ['-session_start'],
            },
        ),
        migrations.CreateModel(
            name='UserChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon_mentioned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_chat_mentions', to='salons.salon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Chat History',
                'verbose_name_plural': 'User Chat Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='chatbot_use_user_id_8a7c07_idx'), models.Index(fields=['intent'], name='chatbot_use_intent_aa4718_idx')],
            },
        ),
    ]
