# Generated by Django 6.0 on 2025-12-28 04:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_alter_salon_created_at_alter_salon_updated_at'),
        ('staff', '0002_employee_delete_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='staff@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(default='Staff Member', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='primary_skill',
            field=models.CharField(choices=[('hair_styling', 'Hair Styling'), ('hair_cutting', 'Hair Cutting'), ('beard_trim', 'Beard Trim'), ('coloring', 'Coloring'), ('spa', 'Spa'), ('massage', 'Massage'), ('nails', 'Nails'), ('makeup', 'Makeup')], default='hair_styling', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('stylist', 'Stylist'), ('barber', 'Barber'), ('specialist', 'Specialist'), ('manager', 'Manager'), ('receptionist', 'Receptionist')], default='stylist', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='salons.salon'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['salon'], name='staff_emplo_salon_i_b72190_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['role'], name='staff_emplo_role_40bae9_idx'),
        ),
    ]
