# Generated by Django 6.0 on 2026-02-16 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift_end_time',
            field=models.TimeField(default=datetime.time(18, 0), help_text='Daily shift end time'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_start_time',
            field=models.TimeField(default=datetime.time(10, 0), help_text='Daily shift start time'),
        ),
    ]
