# Generated by Django 6.0 on 2025-12-19 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='admin',
        ),
        migrations.AddField(
            model_name='salon',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='owner',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'SALON_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_salons', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
