# Generated by Django 6.0 on 2025-12-25 10:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_remove_salon_admin_salon_is_open_salon_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salon',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='salon',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salon',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salon',
            name='hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salon',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salon',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='salon_type',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='salon',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salon',
            name='owner',
            field=models.OneToOneField(limit_choices_to={'role': 'SALON_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='salon', to=settings.AUTH_USER_MODEL),
        ),
    ]
