# Generated by Django 6.0 on 2025-12-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_alter_salon_options_salon_about_salon_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
