# Generated by Django 6.0 on 2026-01-27 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_alter_salon_created_at_alter_salon_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', help_text='City name for location-based filtering', max_length=100),
        ),
        migrations.AddField(
            model_name='salon',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for location services', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for location services', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='pincode',
            field=models.CharField(blank=True, default='', help_text='Postal/ZIP code', max_length=10),
        ),
        migrations.AddField(
            model_name='salon',
            name='state',
            field=models.CharField(blank=True, default='', help_text='State/Region name', max_length=100),
        ),
        migrations.AddIndex(
            model_name='salon',
            index=models.Index(fields=['city', 'is_open'], name='salons_salo_city_84a859_idx'),
        ),
        migrations.AddIndex(
            model_name='salon',
            index=models.Index(fields=['state'], name='salons_salo_state_4d08d0_idx'),
        ),
        migrations.AddIndex(
            model_name='salon',
            index=models.Index(fields=['pincode'], name='salons_salo_pincode_d21661_idx'),
        ),
    ]
