# Generated by Django 6.0 on 2026-02-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_salon_city_salon_latitude_salon_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='blockout_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of ISO date strings for holidays'),
        ),
    ]
