# Generated by Django 6.0 on 2026-02-05 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HairstyleAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(help_text='User uploaded face image', upload_to='hairstyle_uploads/%Y/%m/%d/')),
                ('face_shape', models.CharField(blank=True, choices=[('OVAL', 'Oval'), ('ROUND', 'Round'), ('SQUARE', 'Square'), ('HEART', 'Heart'), ('LONG', 'Long/Oblong'), ('DIAMOND', 'Diamond')], max_length=10, null=True)),
                ('current_hair_length', models.CharField(blank=True, choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], max_length=10, null=True)),
                ('current_hair_color', models.CharField(blank=True, max_length=50, null=True)),
                ('recommendations', models.JSONField(default=list, help_text='List of recommended hairstyles')),
                ('styling_tips', models.JSONField(default=list, help_text='Styling tips for the user')),
                ('recommended_products', models.JSONField(default=list, help_text='Recommended hair products')),
                ('analysis_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex/Other')], default='unisex', max_length=10)),
                ('user_preferences', models.JSONField(default=dict, help_text='User preferences like maintenance level, style preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score of face detection (0-1)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hairstyle_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hairstyle Analysis',
                'verbose_name_plural': 'Hairstyle Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HairstyleRecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_name', models.CharField(max_length=100)),
                ('liked', models.BooleanField(help_text='Did the user like this recommendation?')),
                ('tried', models.BooleanField(default=False, help_text='Did the user try this style?')),
                ('comment', models.TextField(blank=True, help_text='User comments about the recommendation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='hairstyle_ml.hairstyleanalysis')),
            ],
            options={
                'verbose_name': 'Recommendation Feedback',
                'verbose_name_plural': 'Recommendation Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hairstyleanalysis',
            index=models.Index(fields=['user', '-created_at'], name='hairstyle_m_user_id_7ca2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='hairstyleanalysis',
            index=models.Index(fields=['face_shape'], name='hairstyle_m_face_sh_1e3a0c_idx'),
        ),
    ]
